name: Pack and Publish Payroll Library
on:
  push:
    branches: [ master ]

jobs:
  unosquare-payroll:
    uses: unosquare/swan/.github/workflows/lib-ci.yml@master
    with:
      project-name: 'Unosquare.Blazorific'
    secrets:
      github-token: ${{ secrets.GPR_ACCESS_TOKEN }}
