# This GitHub Action simply builds, packs and publishes the package to Nuget.org
# You will need to manually trigger it.
# by @geoperez and @mariodivece
name: Pack and Publish to Nuget.org
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: 'Unosquare.Blazorific'
      PROJECT_FILE_PATH: '/home/runner/work/blazorific/blazorific/Unosquare.Blazorific/Unosquare.Blazorific.csproj'
      BUILD_PATH: '/home/runner/work/blazorific/blazorific/Unosquare.Blazorific/bin/Release/*.nupkg'
      GITHUB_TOKEN: ${{ secrets.GPR_ACCESS_TOKEN }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ env.GITHUB_TOKEN }}
    - name: 🥓 Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
            5.0.x
            6.0.x
    - name: 🏗 Build, Pack and Publish to Nuget.org
      run: |
        dotnet pack ${{ env.PROJECT_FILE_PATH }} --configuration Release -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
        dotnet nuget push ${{ env.BUILD_PATH }} --source https://api.nuget.org/v3/index.json --api-key ${{ env.NUGET_API_KEY }}
        
